pages = [{"l":"index.html","n":"Pretty Metrics","t":"Pretty Metrics","d":"","k":"static"},
{"l":"pretty/metrics.html","n":"pretty.metrics","t":"package pretty.metrics","d":"pretty/metrics","k":"package"},
{"l":"pretty/metrics/Count.html","n":"Count","t":"trait Count","d":"pretty/metrics/Count","k":"trait"},
{"l":"pretty/metrics/Count.html","n":"count","t":"def count: Long","d":"pretty/metrics/Count","k":"def"},
{"l":"pretty/metrics/Counter.html","n":"Counter","t":"trait Counter extends Metric with Count","d":"pretty/metrics/Counter","k":"trait"},
{"l":"pretty/metrics/Gauge.html","n":"Gauge","t":"trait Gauge[T] extends Metric","d":"pretty/metrics/Gauge","k":"trait"},
{"l":"pretty/metrics/Gauge.html","n":"value","t":"def value: T","d":"pretty/metrics/Gauge","k":"def"},
{"l":"pretty/metrics/Histogram.html","n":"Histogram","t":"trait Histogram extends Metric with Statistics","d":"pretty/metrics/Histogram","k":"trait"},
{"l":"pretty/metrics/Meter.html","n":"Meter","t":"trait Meter extends Metric with Rates","d":"pretty/metrics/Meter","k":"trait"},
{"l":"pretty/metrics/Metric.html","n":"Metric","t":"trait Metric","d":"pretty/metrics/Metric","k":"trait"},
{"l":"pretty/metrics/Metric.html","n":"name","t":"def name: String","d":"pretty/metrics/Metric","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"Metrics","t":"class Metrics(val registry: MetricRegistry)","d":"pretty/metrics/Metrics","k":"class"},
{"l":"pretty/metrics/Metrics.html","n":"addCounter","t":"def addCounter(name: String): Metrics","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"addGauge","t":"def addGauge[T](name: String)(gauge: () => T): Metrics","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"addHistogram","t":"def addHistogram(name: String): Metrics","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"addMeter","t":"def addMeter(name: String): Metrics","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"addTimer","t":"def addTimer(name: String): Metrics","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"counter","t":"def counter(name: String): Counter","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"counters","t":"def counters: Seq[Counter]","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"dec","t":"def dec(name: String, count: Long): Metrics","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"gauge","t":"def gauge[T](name: String): Gauge[T]","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"gauges","t":"def gauges: Seq[Gauge[_]]","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"getCounter","t":"def getCounter(name: String): Option[Counter]","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"getGauge","t":"def getGauge[T](name: String): Option[Gauge[T]]","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"getHistogram","t":"def getHistogram(name: String): Option[Histogram]","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"getMeter","t":"def getMeter(name: String): Option[Meter]","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"getTimer","t":"def getTimer(name: String): Option[Timer]","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"histogram","t":"def histogram(name: String): Histogram","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"histograms","t":"def histograms: Seq[Histogram]","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"inc","t":"def inc(name: String, count: Long): Metrics","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"mark","t":"def mark(name: String, count: Long): Metrics","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"meter","t":"def meter(name: String): Meter","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"meters","t":"def meters: Seq[Meter]","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"metrics","t":"def metrics: Seq[Metric]","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"names","t":"def names: Set[String]","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"registry","t":"val registry: MetricRegistry","d":"pretty/metrics/Metrics","k":"val"},
{"l":"pretty/metrics/Metrics.html","n":"remove","t":"def remove(name: String): Metrics","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"reset","t":"def reset(): Metrics","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"time","t":"def time[T](name: String)(event: => T): T","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"timer","t":"def timer(name: String): Timer","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"timers","t":"def timers: Seq[Timer]","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Metrics.html","n":"update","t":"def update(name: String, value: Long): Metrics","d":"pretty/metrics/Metrics","k":"def"},
{"l":"pretty/metrics/Rates.html","n":"Rates","t":"trait Rates extends Count","d":"pretty/metrics/Rates","k":"trait"},
{"l":"pretty/metrics/Rates.html","n":"fifteenMinuteRate","t":"def fifteenMinuteRate: Double","d":"pretty/metrics/Rates","k":"def"},
{"l":"pretty/metrics/Rates.html","n":"fiveMinuteRate","t":"def fiveMinuteRate: Double","d":"pretty/metrics/Rates","k":"def"},
{"l":"pretty/metrics/Rates.html","n":"meanRate","t":"def meanRate: Double","d":"pretty/metrics/Rates","k":"def"},
{"l":"pretty/metrics/Rates.html","n":"oneMinuteRate","t":"def oneMinuteRate: Double","d":"pretty/metrics/Rates","k":"def"},
{"l":"pretty/metrics/Statistics.html","n":"Statistics","t":"trait Statistics extends Count","d":"pretty/metrics/Statistics","k":"trait"},
{"l":"pretty/metrics/Statistics.html","n":"max","t":"def max: Long","d":"pretty/metrics/Statistics","k":"def"},
{"l":"pretty/metrics/Statistics.html","n":"mean","t":"def mean: Double","d":"pretty/metrics/Statistics","k":"def"},
{"l":"pretty/metrics/Statistics.html","n":"median","t":"def median: Double","d":"pretty/metrics/Statistics","k":"def"},
{"l":"pretty/metrics/Statistics.html","n":"min","t":"def min: Long","d":"pretty/metrics/Statistics","k":"def"},
{"l":"pretty/metrics/Statistics.html","n":"stdDev","t":"def stdDev: Double","d":"pretty/metrics/Statistics","k":"def"},
{"l":"pretty/metrics/Timer.html","n":"Timer","t":"trait Timer extends Metric with Rates with Statistics","d":"pretty/metrics/Timer","k":"trait"},
{"l":"docs/index.html","n":"Pretty Metrics","t":"Pretty Metrics","d":"","k":"static"}];